data:
    img_dir: "data/SALICON/images/train"
    heatmap_dir: "data/SALICON/heatmaps/train"
    batch_size: 32

model:
    input_size: [224, 224]
    "network": "UNET"

training:
    lr: 1e-4
    weight_decay: 1e-5
    epochs: 50
    use_gpu: False

logging:
    checkpoint_dir: "checkpoints"
    experiment_name: "gaze_prediction"
