# Configuration for gaze prediction model training

# General settings
experiment_name: "gaze_predictor"
seed: 42

# Data configuration
data:
  img_dir: "datasets/SALICON/train/images"
  heatmap_dir: "datasets/SALICON/train/maps"
  batch_size: 8
  val_split: 0.1

# Model configuration
model:
  backbone: "resnet18"
  pretrained: true
  normalize_heatmap: true
  smooth_sigma: 2.0

# Training parameters
training:
  epochs: 20
  lr: 0.0001
  weight_decay: 0.00001
  use_gpu: true
  early_stopping_patience: 5

# Logging
logging:
  checkpoint_dir: "checkpoints/gaze_model"
  log_interval: 10
  val_interval: 1
  tensorboard: true